### ISSUE TITLE
Some steps are very slow 

### ISSUE THREAD

**Issue by prockenschaub** [rvandewater/ReciPys#7]
Steps like `StepHistorical` and `StepImputeFill` can take a long time. We may want to think about ways to speed those up. For example, I have in the past been able to speed up pandas `ffill` by inserting stopping rows between patients and then running `ffill` on the ungrouped dataframe.

**Comment by prockenschaub** [comment]
Performance fo `StepImputeFill` fixed by #14.

**Comment by rvandewater** [comment]
Polars backend should increase speed #20 .
